# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # 当推送到 main 分支时触发
  push:
    branches: ["main"]

  # 允许在 Actions 选项卡中手动触发
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 确保只有一个部署任务在运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Ruby 环境
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # 指定您的 Ruby 版本
          bundler-cache: true # 自动运行 'bundle install' 并缓存已安装的 gems

      - name: 安装依赖
        run: |
          gem install bundler
          bundle install

      - name: 使用 Jekyll 构建网站
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
